/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproj.databaseproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import java.awt.*;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;


/**
 *
 * @author hp
 */
public class CustomerSignUp extends javax.swing.JFrame {

    /**
     * Creates new form CustomerSignUp
     */
    String firstname;
    String username;
    String lastname;
    String email;
    String password;
    String date;
    String phonenumber;
    String salary;
    String newusername="";
    String ID="";
    String sex="";
    int flag=0;
    public CustomerSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FirstnameTF = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        LastnameTF = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        EmailTF = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        UsernameTF = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        PhoneNumberTF = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();
        PasswordLabel = new javax.swing.JLabel();
        BirthdateLabel = new javax.swing.JLabel();
        SignUpCustomerButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();
        ShutDownLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Sex = new javax.swing.JLabel();
        SexChooser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 233, 43));
        jPanel1.setForeground(new java.awt.Color(255, 233, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel1.setText("Customer Sign Up!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 290, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 10));

        FirstnameTF.setBackground(new java.awt.Color(255, 233, 43));
        FirstnameTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FirstnameTF.setBorder(null);
        jPanel1.add(FirstnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, -1));

        FirstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FirstNameLabel.setText("First Name");
        jPanel1.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, 10));

        LastnameTF.setBackground(new java.awt.Color(255, 233, 43));
        LastnameTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LastnameTF.setBorder(null);
        jPanel1.add(LastnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LastNameLabel.setText("Last Name");
        jPanel1.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 180, 10));

        EmailTF.setBackground(new java.awt.Color(255, 233, 43));
        EmailTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailTF.setBorder(null);
        jPanel1.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 180, -1));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email.setText("Email");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 180, 10));

        UsernameTF.setBackground(new java.awt.Color(255, 233, 43));
        UsernameTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTF.setBorder(null);
        jPanel1.add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 180, -1));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameLabel.setText("Username");
        jPanel1.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 180, 10));

        PhoneNumberTF.setBackground(new java.awt.Color(255, 233, 43));
        PhoneNumberTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNumberTF.setBorder(null);
        jPanel1.add(PhoneNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 180, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");
        jPanel1.add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 233, 43));
        jPasswordField1.setEchoChar('\u25CF');
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 180, 27));

        ShowPasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        ShowPasswordCheckBox.setText("Show Password");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 20));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        BirthdateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BirthdateLabel.setText("Birth Date");
        jPanel1.add(BirthdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, -1));

        SignUpCustomerButton.setBackground(new java.awt.Color(0, 0, 0));
        SignUpCustomerButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SignUpCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpCustomerButton.setText("Sign Up");
        SignUpCustomerButton.setBorder(new javax.swing.border.MatteBorder(null));
        SignUpCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpCustomerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 80, 30));

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Back.gif")); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 80, -1));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\SpongeBob.gif")); // NOI18N
        BackgroundLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BackgroundLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 230, -1));

        ShutDownLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\ShutDown.gif")); // NOI18N
        ShutDownLabel.setText("    ");
        ShutDownLabel.setToolTipText("");
        ShutDownLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ShutDownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutDownLabelMouseClicked(evt);
            }
        });
        jPanel1.add(ShutDownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 70, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 190, -1));

        Sex.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sex.setText("Sex");
        jPanel1.add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        SexChooser.setBackground(new java.awt.Color(0, 0, 0));
        SexChooser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SexChooser.setForeground(new java.awt.Color(255, 233, 43));
        SexChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel1.add(SexChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPasswordCheckBox.isSelected())
        {
            jPasswordField1.setEchoChar((char) 0);
        }
        else
        {
            jPasswordField1.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void ShutDownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutDownLabelMouseClicked
        // TODO add your handling code here:
        UIManager UI=new UIManager();
        UI.put("OptionPane.background",new ColorUIResource(0,0,0));
        UI.put("OptionPane.messageForeground",new ColorUIResource(0,0,0));
        UI.put("Panel.background",new ColorUIResource(0,0,0));
        JLabel label = new JLabel ("Are you sure you want to exit this program?");
        label.setForeground(new java.awt.Color(255,233,43));
        ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\OneDrive\\Desktop\\E-Learning (Mira)\\(7) Second Semester 2021-2022\\DataBase\\DatabaseProject\\Question.gif");
        int  result=JOptionPane .showOptionDialog(null, label, "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,icon, null,null);
        if(result==0)
        this.dispose();
    }//GEN-LAST:event_ShutDownLabelMouseClicked

    private void SignUpCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpCustomerButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(UsernameTF.getText().isEmpty()||EmailTF.getText().isEmpty()||
               FirstnameTF.getText().isEmpty()||LastnameTF.getText().isEmpty()||
               String.valueOf(jPasswordField1.getPassword()).isEmpty()||
               (jDateChooser1.getDate()==null)||PhoneNumberTF.getText().isEmpty())
            {
                UIManager UI=new UIManager();
                UI.put("OptionPane.background",new ColorUIResource(0,0,0));
                UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
                UI.put("Panel.background",new ColorUIResource(0,0,0));
                ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Error.gif");
                JOptionPane.showMessageDialog(this, "Invalid input,fill all information", "Error", JOptionPane.ERROR_MESSAGE, icon);
            }
            else
            {
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String url="jdbc:oracle:thin:@localhost:1521:orcl";
                Connection con=DriverManager.getConnection(url,"c##scott","tiger");
                con.setAutoCommit(false);
                username=UsernameTF.getText();     
                String sqlStmt0="select * from account where username='"+username+"'";
                PreparedStatement PrS0=con.prepareStatement(sqlStmt0);
                ResultSet rs0=PrS0.executeQuery();
                if(rs0.next())
                {  
                  UIManager UI=new UIManager();
                  UI.put("OptionPane.background",new ColorUIResource(0,0,0));
                  UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
                  UI.put("Panel.background",new ColorUIResource(0,0,0));
                  ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Error.gif");
                  JOptionPane.showMessageDialog(this, "Account already exists", "Error", JOptionPane.ERROR_MESSAGE, icon); 
                  con.commit();
                }
                else
                {
                    String sqlStmt="";
                    if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@gmail.com"))==10 )&&
                      EmailTF.getText().contains("@gmail.com"))
                    {                     
                        flag=0;
                        email=EmailTF.getText();
                    }
                    else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@hotmail.com"))==12 )&&
                            EmailTF.getText().contains("@hotmail.com"))    
                    {                    
                        flag=0;
                        email=EmailTF.getText();
                    }
                    else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@yahoo.com"))==10 )&&
                            EmailTF.getText().contains("@yahoo.com"))
                    {                      
                        flag=0;
                        email=EmailTF.getText();
                    }
                    else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@najah.edu"))==10 )&&
                            EmailTF.getText().contains("@najah.edu"))
                    {                       
                        flag=0;
                        email=EmailTF.getText();
                    }
                    else
                    {
                        flag=1;
                        JOptionPane.showMessageDialog(this,"Invalid Email","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    if((flag==0)&&(!String.valueOf(jPasswordField1.getPassword()).isEmpty()))
                    {
                        flag=0;
                        password=String.valueOf(jPasswordField1.getPassword()); 
                        if(password.contains(UsernameTF.getText()))
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this,"Password cannot contain the username.Try again","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else if(password.length()<8)
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this,"Password must has 8 characters or more.Try again","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else
                        {
                            flag=0;
                            password=String.valueOf(jPasswordField1.getPassword());
                        }
                    }
                    if(flag==0)
                    {
                        password=String.valueOf(jPasswordField1.getPassword());
                        firstname=FirstnameTF.getText();
                        lastname=LastnameTF.getText();
                        if(SexChooser.getSelectedItem().toString().equals("Female"))
                            sex="F";
                        else
                            sex="M";
                        email=EmailTF.getText();
                        phonenumber=PhoneNumberTF.getText();
                        DateFormat DF = DateFormat.getDateInstance(DateFormat.MEDIUM);
                        String date1=DF.format(jDateChooser1.getDate());
                        String []dateSplit=date1.split(" ");
                        String month=dateSplit[0];
                        String year=dateSplit[2];
                        String []daySplit=dateSplit[1].split(",");
                        String day=daySplit[0];
                        date=day+"-"+month+"-"+year;
                        date=date.toLowerCase();
                        System.out.println(firstname+"\n"+lastname+"\n"+sex+"\n"+email+"\n"+username+"\n"+password+"\n"+date+"\n"+phonenumber);                    
                        String sqlStmt1="insert into account values('"+username+"','"+password+"')";
                        PreparedStatement PrS1=con.prepareStatement(sqlStmt1);
                        ResultSet rs1=PrS1.executeQuery();
                        con.commit();
                        String sqlStmt2="select count(*) from customer";
                        PreparedStatement PrS2=con.prepareStatement(sqlStmt2);
                        ResultSet rs2=PrS2.executeQuery();
                        int count=0;
                        if(rs2.next())
                        {
                            count=rs2.getInt(1);
                        }
                        count++;
                        ID=""+count;
                        String sqlStmt3="insert into customer values('"+ID+"','"+firstname+"','"+lastname+"','"+sex+"','"+date+"','"+email+"','"+username+"','"+phonenumber+"',0)";
                        PreparedStatement PrS3=con.prepareStatement(sqlStmt3);
                        ResultSet rs3=PrS3.executeQuery();
                        con.commit();
                        UIManager UI=new UIManager();
                        UI.put("OptionPane.background",new ColorUIResource(0,0,0));
                        UI.put("OptionPane.messageForeground",new ColorUIResource(0,0,0));
                        UI.put("Panel.background",new ColorUIResource(0,0,0));
                        JLabel label = new JLabel ("Account Created.Do you want to sign in?");
                        label.setForeground(new java.awt.Color(255,233,43));
                        ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\OneDrive\\Desktop\\E-Learning (Mira)\\(7) Second Semester 2021-2022\\DataBase\\DatabaseProject\\Question.gif");
                        int  result=JOptionPane .showOptionDialog(null, label, "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,icon, null,null);
                        if(result==0)
                        {
                            this.toBack();
                            CustomerSignIn CSI=new CustomerSignIn();
                            CSI.setVisible(true);
                            CSI.toFront();
                            this.dispose();
                        }
                        else
                        {
                            System.exit(0);
                        }
                        
                    } 
                }
            }
        }
        catch(Exception ex){
           // System.out.println(ex.toString());
           ex.printStackTrace();
        }
    }//GEN-LAST:event_SignUpCustomerButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.toBack();
        CustomerSignIn CSI=new CustomerSignIn();
        CSI.setVisible(true);
        CSI.toFront();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstnameTF;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastnameTF;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTF;
    private javax.swing.JLabel Sex;
    private javax.swing.JComboBox<String> SexChooser;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JLabel ShutDownLabel;
    private javax.swing.JButton SignUpCustomerButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTF;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
