/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproj.databaseproject;
import java.sql.*;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author hp
 */
public class CustomerSignIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerSignIn
     */
    public CustomerSignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        CustomerSignInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameSignIn = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        PasswordLabel = new javax.swing.JLabel();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        ShutDownLabel = new javax.swing.JLabel();
        ForgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 233, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 50, 10));

        CustomerSignInButton.setBackground(new java.awt.Color(0, 0, 0));
        CustomerSignInButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerSignInButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomerSignInButton.setText("Sign In");
        CustomerSignInButton.setBorder(null);
        CustomerSignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerSignInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerSignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel1.setText("Customer Sign In Portal!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Don't have an account?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 440, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Sign Up");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\MrCrabs.gif")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 220));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameLabel.setText("Username");
        jPanel1.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        UsernameSignIn.setBackground(new java.awt.Color(255, 233, 43));
        UsernameSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameSignIn.setBorder(null);
        UsernameSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameSignInActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 180, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 233, 43));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 27));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, 10));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        ShowPasswordCheckBox.setBackground(new java.awt.Color(255, 233, 43));
        ShowPasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        ShowPasswordCheckBox.setText("Show Password");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 20));

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Back.gif")); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, -1));

        ShutDownLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\SmallShutDown.gif")); // NOI18N
        ShutDownLabel.setText("    ");
        ShutDownLabel.setToolTipText("");
        ShutDownLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ShutDownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutDownLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShutDownLabelMouseEntered(evt);
            }
        });
        jPanel1.add(ShutDownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 5, 50, -1));

        ForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ForgotPassword.setText("Forgot Password?");
        ForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPasswordCheckBox.isSelected())
        {
            jPasswordField1.setEchoChar((char) 0);
        }
        else
        {
            jPasswordField1.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        this.toBack();
        Welcome W=new Welcome();
        W.setVisible(true);
        W.toFront();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ShutDownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutDownLabelMouseClicked
        // TODO add your handling code here:
        UIManager UI=new UIManager();
        UI.put("OptionPane.background",new ColorUIResource(0,0,0));
        UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
        UI.put("Panel.background",new ColorUIResource(0,0,0));
        JLabel label = new JLabel ("Are you sure you want to exit this program?");
        label.setForeground(new java.awt.Color(255,233,43));
        ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\OneDrive\\Desktop\\E-Learning (Mira)\\(7) Second Semester 2021-2022\\DataBase\\DatabaseProject\\Question.gif");
        int  result=JOptionPane .showOptionDialog(null, label, "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,icon, null,null);
        if(result==0)
        this.dispose();
    }//GEN-LAST:event_ShutDownLabelMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.toBack();
        CustomerSignUp CSU=new CustomerSignUp();
        CSU.setVisible(true);
        CSU.toFront();
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void CustomerSignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerSignInButtonActionPerformed
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(url,"c##scott","tiger");
            String username=UsernameSignIn.getText();
            String password=String.valueOf(jPasswordField1.getPassword());     
            String sqlStmt="select * from account where username='"+username+"' and password='"
                    +password+"'";
            PreparedStatement PrS=con.prepareStatement(sqlStmt);
            ResultSet rs=PrS.executeQuery();
            if(rs.next())
            {  
              UIManager UI=new UIManager();
              UI.put("OptionPane.background",new ColorUIResource(0,0,0));
              UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
              UI.put("Panel.background",new ColorUIResource(0,0,0));
              JLabel label = new JLabel ("Are you sure you want to exit this program?");
              label.setForeground(new java.awt.Color(255,233,43));
              ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Success.gif");
              JOptionPane.showMessageDialog(this, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE, icon);
              String firstname="";
              String nameQuery="select first_name from customer where username='"+username+"'";
              PreparedStatement PrS1=con.prepareStatement(nameQuery);
              ResultSet rs1=PrS1.executeQuery();
              if(rs1.next())
              firstname=rs1.getString(1);
              this.toBack();
              Shopping S=new Shopping(firstname,username);
              S.setVisible(true);
              S.toFront();
              this.dispose();
            }
            else
            {
              UIManager UI=new UIManager();
              UI.put("OptionPane.background",new ColorUIResource(0,0,0));
              UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
              UI.put("Panel.background",new ColorUIResource(0,0,0));
              ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Error.gif");
              JOptionPane.showMessageDialog(this, "Invalid Creditentials", "Error", JOptionPane.ERROR_MESSAGE, icon);  
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
            
    }//GEN-LAST:event_CustomerSignInButtonActionPerformed

    private void UsernameSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameSignInActionPerformed

    private void ShutDownLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutDownLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ShutDownLabelMouseEntered

    private void ForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordMouseClicked
        // TODO add your handling code here:
        try{
            String Email="";
            UIManager UI=new UIManager();
            UI.put("OptionPane.background",new ColorUIResource(0,0,0));
            UI.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
            UI.put("Panel.background",new ColorUIResource(0,0,0));
            UI.put("Button.Background",new ColorUIResource(255,233,43));
            ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Question.gif");
            Email=(String) JOptionPane.showInputDialog(this,"Please enter your email","Email Query", JOptionPane.INFORMATION_MESSAGE, icon, null, "");
            while(Email.isEmpty())
            {
                UIManager UI1=new UIManager();
                UI1.put("OptionPane.background",new ColorUIResource(0,0,0));
                UI1.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
                UI1.put("Panel.background",new ColorUIResource(0,0,0));
                UI1.put("Button.Background",new ColorUIResource(255,233,43));
                ImageIcon icon1=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Error.gif");
                JOptionPane.showMessageDialog(this,"Error!Make sure to fill in your email correctly","Error",JOptionPane.ERROR_MESSAGE,icon);
                UIManager UI4=new UIManager();
                UI4.put("OptionPane.background",new ColorUIResource(0,0,0));
                UI4.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
                UI4.put("Panel.background",new ColorUIResource(0,0,0));
                UI4.put("Button.Background",new ColorUIResource(255,233,43));
                ImageIcon icon4=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Question.gif");
                Email=(String) JOptionPane.showInputDialog(this,"Please enter your email","Email Query", JOptionPane.INFORMATION_MESSAGE, icon, null, "");

            }
            Random random=new Random();
            int randomInt=0;
            randomInt=random.nextInt(1000,9999);
            String randomString=""+randomInt;
            // TODO add your handling code here:
            try {
                sendEmail(Email,randomString);
            } catch (Exception ex) {
                System.out.println("btn\t"+ex.toString());
            }
            UIManager UI2=new UIManager();
            UI2.put("OptionPane.background",new ColorUIResource(0,0,0));
            UI2.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
            UI2.put("Panel.background",new ColorUIResource(0,0,0));
            UI2.put("Button.Background",new ColorUIResource(255,233,43));
            ImageIcon icon2=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Question.gif");
            String enteredCode=(String) JOptionPane.showInputDialog(this,"Enter the confirmation code","Confirmation", JOptionPane.INFORMATION_MESSAGE, icon, null, "");
            if(enteredCode.equals(randomString))
            {
                UIManager UI3=new UIManager();
                UI3.put("OptionPane.background",new ColorUIResource(0,0,0));
                UI3.put("OptionPane.messageForeground",new ColorUIResource(255,233,43));
                UI3.put("Panel.background",new ColorUIResource(0,0,0));
                UI3.put("Button.Background",new ColorUIResource(255,233,43));
                ImageIcon icon6=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Question.gif");
                String password=(String) JOptionPane.showInputDialog(this,"Enter your new password","Password Query", JOptionPane.INFORMATION_MESSAGE, icon6, null, "");
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String url="jdbc:oracle:thin:@localhost:1521:orcl";
                Connection con=DriverManager.getConnection(url,"c##scott","tiger");
                con.setAutoCommit(false);
                String sqlStmt="select username from customer where email='"+Email+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                String username="";
                if(rs.next())
                {
                    username=rs.getString(1);
                }
                con.commit();
                String sqlStmt1="update account set password='"+password+"' where username='"+username+"'";
                PreparedStatement PrS1=con.prepareStatement(sqlStmt1);
                ResultSet rs1=PrS1.executeQuery();
                con.commit();
                System.out.println("Match");
            }else
            {
                ImageIcon icon5=new ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Error.gif");
                JOptionPane.showMessageDialog(this,"Code doesn't match the one sent to your email","Error",JOptionPane.ERROR_MESSAGE,icon5);
            }
        }catch(Exception ex)
        {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_ForgotPasswordMouseClicked
    public static void sendEmail(String e,String number) throws Exception
    {
        JavaEmailSender.sendMail(e,number);
    }
       
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        jPasswordField1.setEchoChar('\u25CF');
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CustomerSignInButton;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JLabel ShutDownLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
