/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproj.databaseproject;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JComponent;
import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.sql.*;
import java.text.DateFormat;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.basic.BasicScrollBarUI;

/**
 *
 * @author miraj
 */
public class EditProfileAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form EditProfileAdministrator
     */
    String firstname;
    String username;
    String lastname;
    String email;
    String password;
    String date;
    String phonenumber;
    String salary;
    String newusername="";
    String ID="";
    int flag=0;
    public EditProfileAdministrator(String fn,String u) {
        firstname=fn;
        username=u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb1_image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        FirstNameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LastNameTF = new javax.swing.JTextField();
        SalaryTF = new javax.swing.JTextField();
        PhoneNumberTF = new javax.swing.JTextField();
        SaveChangesButton = new javax.swing.JButton();
        Email = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        ShutDownLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\Back.gif")); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jPanel1.setBackground(new java.awt.Color(255, 233, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb1_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\ChandlerBing.png")); // NOI18N
        jPanel1.add(lb1_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 72, 234, 300));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Profile Picture");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jButton1.setBackground(new java.awt.Color(39, 188, 234));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Attatch");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 60, 37));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel4.setText("Edit Profile");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 233, 43));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 20));

        FirstNameTF.setBackground(new java.awt.Color(255, 233, 43));
        FirstNameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstNameTF.setBorder(null);
        jPanel2.add(FirstNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 48, 145, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("First Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 100, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 20));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 150, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 104, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Start Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 104, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 104, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Salary");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 104, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Phone Number");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 30));

        LastNameTF.setBackground(new java.awt.Color(255, 233, 43));
        LastNameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastNameTF.setBorder(null);
        jPanel2.add(LastNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 88, 145, 20));

        SalaryTF.setBackground(new java.awt.Color(255, 233, 43));
        SalaryTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalaryTF.setBorder(null);
        SalaryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryTFActionPerformed(evt);
            }
        });
        jPanel2.add(SalaryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 145, 20));

        PhoneNumberTF.setBackground(new java.awt.Color(255, 233, 43));
        PhoneNumberTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberTF.setBorder(null);
        jPanel2.add(PhoneNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 145, 20));

        SaveChangesButton.setBackground(new java.awt.Color(39, 188, 234));
        SaveChangesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaveChangesButton.setText("Save Changes ");
        SaveChangesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SaveChangesButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SaveChangesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 40));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 104, 30));

        EmailTF.setBackground(new java.awt.Color(255, 233, 43));
        EmailTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailTF.setBorder(null);
        jPanel2.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 127, 145, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 233, 43));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 20));

        ShowPasswordCheckBox.setBackground(new java.awt.Color(255, 233, 43));
        ShowPasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        ShowPasswordCheckBox.setText("Show Password");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 20));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Username");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 104, 30));

        UsernameTF.setBackground(new java.awt.Color(255, 233, 43));
        UsernameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameTF.setBorder(null);
        jPanel2.add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 167, 145, 20));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 440, 490));

        ShutDownLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\miraj\\Documents\\DatabaseProject\\ShutDown.gif")); // NOI18N
        ShutDownLabel.setText("    ");
        ShutDownLabel.setToolTipText("");
        ShutDownLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ShutDownLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutDownLabelMouseClicked(evt);
            }
        });
        jPanel1.add(ShutDownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 745, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        Image getAbsolutePath=null;
        ImageIcon icon=new ImageIcon(filename);
        Image image= icon.getImage().getScaledInstance(lb1_image.getWidth(),lb1_image.getHeight(),Image.SCALE_SMOOTH);
        lb1_image.setIcon(icon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ShutDownLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutDownLabelMouseClicked
        // TODO add your handling code here:
        UIManager UI=new UIManager();
        UI.put("OptionPane.background",new ColorUIResource(0,0,0));
        UI.put("OptionPane.messageForeground",new ColorUIResource(0,0,0));
        UI.put("Panel.background",new ColorUIResource(0,0,0));
        JLabel label = new JLabel ("Are you sure you want to exit this program?");
        label.setForeground(new java.awt.Color(255,233,43));
        ImageIcon icon=new ImageIcon("C:\\Users\\miraj\\OneDrive\\Desktop\\E-Learning (Mira)\\(7) Second Semester 2021-2022\\DataBase\\DatabaseProject\\Question.gif");
        int  result=JOptionPane .showOptionDialog(null, label, "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,icon, null,null);
        if(result==0)
        this.dispose();
    }//GEN-LAST:event_ShutDownLabelMouseClicked

    private void SaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesButtonActionPerformed
        // TODO add your handling code here:
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con=DriverManager.getConnection(url,"c##scott","tiger");
            con.setAutoCommit(false);
            String sqlStmt="";
            if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@gmail.com"))==10 )&&
                    EmailTF.getText().contains("@gmail.com")     
               )
            {                     
                flag=0;
                email=EmailTF.getText();
                System.out.println("\n"+email+"  "+username);
                sqlStmt="update manager set email='"+email+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@hotmail.com"))==12 )&&
                    EmailTF.getText().contains("@hotmail.com")     
               )
            {                    
                flag=0;
                email=EmailTF.getText();
                System.out.println("\n"+email+"  "+username);
                sqlStmt="update manager set email='"+email+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@yahoo.com"))==10 )&&
                    EmailTF.getText().contains("@yahoo.com")     
               )
            {                      
                flag=0;
                email=EmailTF.getText();
                System.out.println("\n"+email+"  "+username);
                sqlStmt="update manager set email='"+email+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            else if(( (EmailTF.getText().length() - EmailTF.getText().indexOf("@najah.edu"))==10 )&&
                    EmailTF.getText().contains("@najah.edu")     
               )
            {                       
                flag=0;
                email=EmailTF.getText();
                sqlStmt="update manager set email='"+email+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            else
            {
                if(EmailTF.getText().isEmpty())
                    flag=0;
                else{
                flag=1;
                JOptionPane.showMessageDialog(this,"Invalid Email","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
            if(!String.valueOf(jPasswordField1.getPassword()).isEmpty())
            {
                flag=0;
                password=String.valueOf(jPasswordField1.getPassword());
                sqlStmt="select password from account where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                String passwordSQL="";
                if(rs.next())
                passwordSQL=rs.getString(1);
                if(password.equals(passwordSQL)||password.contains(passwordSQL))
                {
                    flag=1;
                    JOptionPane.showMessageDialog(this,"Password must be different than the previous one","Error",JOptionPane.ERROR_MESSAGE);
                } 
                else if(password.contains(username))
                {
                    flag=1;
                    JOptionPane.showMessageDialog(this,"Password cannot contain the username","Error",JOptionPane.ERROR_MESSAGE);
                }
                else if(password.length()<8)
                {
                    flag=1;
                    JOptionPane.showMessageDialog(this,"Password must has 8 characters or more","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    String sqlStmt1="update account set password='"+password+"' where username='"+username+"'";
                    PreparedStatement PrS1=con.prepareStatement(sqlStmt1);
                    ResultSet rs1=PrS1.executeQuery();
                    con.commit();
                }
                con.commit();
            }
            if((flag==0)&&(!FirstNameTF.getText().isEmpty()))
            {
                firstname=FirstNameTF.getText();
                System.out.println(firstname+"  "+username);
                sqlStmt="update manager set first_name='"+firstname+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            if((flag==0)&&(!LastNameTF.getText().isEmpty()))
            {
                lastname=LastNameTF.getText();
                System.out.println(lastname+"  "+username);
                sqlStmt="update manager set last_name='"+lastname+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            
            if((flag==0)&&(!(jDateChooser1.getDate()==null)))
            {
                DateFormat DF = DateFormat.getDateInstance(DateFormat.MEDIUM);
                String date1=DF.format(jDateChooser1.getDate());
                String []dateSplit=date1.split(" ");
                String month=dateSplit[0];
                String year=dateSplit[2];
                String []daySplit=dateSplit[1].split(",");
                String day=daySplit[0];
                date=day+"-"+month+"-"+year;
                sqlStmt="update manager set start_date='"+date+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            
            if((flag==0)&&(!SalaryTF.getText().isEmpty()))
            {
                salary=SalaryTF.getText();
                sqlStmt="update manager set salary='"+salary+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            if((flag==0)&&(!PhoneNumberTF.getText().isEmpty()))
            {
                phonenumber=PhoneNumberTF.getText();
                sqlStmt="update manager set phone_number='"+phonenumber+"' where username='"+username+"'";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                con.commit();
            }
            if((flag==0)&&(!UsernameTF.getText().isEmpty()))
            {
                sqlStmt="select manager.*,account.password from manager,account where manager.username=account.username";
                PreparedStatement PrS=con.prepareStatement(sqlStmt);
                ResultSet rs=PrS.executeQuery();
                while(rs.next())
                {   
                    ID=rs.getString(1);
                    firstname=rs.getString(2);
                    lastname=rs.getString(3);
                    date=rs.getDate(5).toString();
                    System.out.print(date);
                    email=rs.getString(6);
                    phonenumber=rs.getString(8);
                    salary=""+rs.getInt(9);
                    password=rs.getString(10);
                }
                String dateSplit[]=date.split("-");
                String day=dateSplit[2];
                String year=dateSplit[0];
                String month="";
                if(dateSplit[1].contains("12"))
                    month="dec";
                else if(dateSplit[1].contains("11"))
                    month="nov";
                else if(dateSplit[1].contains("10"))
                    month="oct";
                else if(dateSplit[1].contains("9"))
                    month="sep";
                else if(dateSplit[1].contains("8"))
                    month="aug";
                else if(dateSplit[1].contains("7"))
                    month="jul";
                else if(dateSplit[1].contains("6"))
                    month="jun";
                else if(dateSplit[1].contains("5"))
                    month="may";
                else if(dateSplit[1].contains("4"))
                    month="apr";
                else if(dateSplit[1].contains("3"))
                    month="mar";
                else if(dateSplit[1].contains("2"))
                    month="feb";
                else if(dateSplit[1].contains("1"))
                    month="jan";
                date=day+"-"+month+"-"+year;   
                System.out.println("old username:\t"+username);

                newusername=UsernameTF.getText();
                con.commit();
                String sqlStmt1="delete from manager where username='"+username+"'";
                PreparedStatement PrS1=con.prepareStatement(sqlStmt1);
                ResultSet rs1=PrS1.executeQuery();
                con.commit();
                
                String sqlStmt2="delete from account where username='"+username+"'";
                PreparedStatement PrS2=con.prepareStatement(sqlStmt2);
                ResultSet rs2=PrS2.executeQuery();
                con.commit();
                
                ID=""+(Integer.parseInt(ID)+1);
                
                System.out.print(firstname+"\n"+lastname+"\n"+date+"\n"+email+"\n"+phonenumber+"\n"+salary+"\n"+ newusername+"\n"+password);
                System.out.println("Passowrd:\t"+password);
                String sqlStmt3="insert into account values ('"+newusername+"','"+password+"')";
                PreparedStatement PrS3=con.prepareStatement(sqlStmt3);
                ResultSet rs3=PrS3.executeQuery();
                con.commit();
                
                String sqlStmt4="insert into manager values ('"+ID+"','"+firstname+"','"+lastname+"','M','"+date+"','"+email+"','"+ newusername +"','"+phonenumber+"','"+salary+"')";
                PreparedStatement PrS4=con.prepareStatement(sqlStmt4);
                ResultSet rs4=PrS4.executeQuery();
                username=newusername;
                con.commit();
            }
            
        }catch(Exception ex){
            System.out.println("Save Changes\t"+ex.toString());
        }
            
    }//GEN-LAST:event_SaveChangesButtonActionPerformed

    
    
    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPasswordCheckBox.isSelected())
        {
            jPasswordField1.setEchoChar((char) 0);
        }
        else
        {
            jPasswordField1.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void SalaryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryTFActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.toBack();
        AdministratorPortal AP=new AdministratorPortal(firstname,username);
        AP.setVisible(true);
        AP.toFront();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditProfileAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField LastNameTF;
    private javax.swing.JTextField PhoneNumberTF;
    private javax.swing.JTextField SalaryTF;
    private javax.swing.JButton SaveChangesButton;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JLabel ShutDownLabel;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb1_image;
    // End of variables declaration//GEN-END:variables
}
